version: '3.8'

services:
  react-app:
    build:
      context: ./auth-ui
      dockerfile: Dockerfile
    depends_on:
      - dotnet
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      - PORT=3000
      - PROXY_API=http://localhost:5273

  dotnet:
    build:
      context: ./dotnet-backend
      dockerfile: Dockerfile
    ports:
      - "5273:5273"
    networks:
      - my_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_CONNECTION_STRING=mongodb://mongo:27018
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - my_network
    restart: on-failure
    volumes:
      -  ./portal:/backup
      - ./database:/data/db 
    command: mongorestore /backup --host mongo:27017

volumes:
  dbdata:


networks:
  my_network:
    driver: bridge
